Add bigquery support
snowplow/dbt-snowplow-ecommerce pull request #1
Opened 2022-11-17 12:08 UTC by emielver

## Description & motivation
Adding support for BigQuery

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [x] I have added ~tests &~ descriptions to my models (and macros if applicable)
- [x] I have raised a [documentation](https://github.com/snowplow/documentation) PR if applicable (Link [here](https://github.com/snowplow/documentation/pull/190))

2022-11-17 15:21 UTC, rlh1994 commented on models/base/scratch/bigquery/snowplow_ecommerce_base_events_this_run.sql
> +    a.contexts_ecommerce_tracking_checkout_step_1_0_0[safe_offset(0)].payment_method as checkout_payment_method,
❓ /🔧 Will do a proper review at a later date, just looking around could you use the `snowplow_utils.combine_column_versions` macro here? It would protect against small schema chagnes and also slightly simplify the code?

2022-11-17 22:31 UTC, emielver commented on models/base/scratch/bigquery/snowplow_ecommerce_base_events_this_run.sql
> +    a.contexts_ecommerce_tracking_checkout_step_1_0_0[safe_offset(0)].payment_method as checkout_payment_method,
Yep, great suggestion and added!

2022-11-18 12:34 UTC, rlh1994 requested changes
Will review the doc and yml files in another review

2022-11-18 12:34 UTC, rlh1994 commented on README.md
> +
💡 Do we also require some form of ecommerce events to be tracked? Is there any specific SDE or context we expect them to have to work with this?

2022-11-18 12:34 UTC, rlh1994 commented on dbt_project.yml
> +    snowplow__upsert_lookback_days: 30
🔧 Can you just confirm which of these we actually use in this package, for example it doesn't seem like we use the hearbeat or even the ua_bot_filter at the moment? Might be some others as well.

2022-11-18 12:34 UTC, rlh1994 commented on macros/bigquery/context_fields.sql
> +      {'field':('is_guest', 'ecommerce_user_is_guest'), 'dtype':'boolea'}
🛑  _Boolea_

2022-11-18 12:34 UTC, rlh1994 commented on macros/event_name_filter.sql
> +    true
🛑 if we're going to `lower` the table you should also `lower` the input list.

2022-11-18 12:34 UTC, rlh1994 commented on macros/snowplow_delete_from_manifest.sql
> +{% endmacro %}
❓ Where do we use this?

2022-11-18 12:34 UTC, rlh1994 commented on models/base/manifest/base_manifest.yml
> +        description: The latest event consumed by the model, based on `collector_tstamp`
```suggestion
        description: The timestamp of the latest event consumed by the model, based on `collector_tstamp`
```

2022-11-18 12:34 UTC, rlh1994 commented on models/base/manifest/snowplow_ecommerce_base_sessions_lifecycle_manifest.sql
> +
🔧 Do you need to exclude quarenteened sessions here as well?

2022-11-18 12:34 UTC, rlh1994 commented on models/base/scratch/bigquery/snowplow_ecommerce_base_events_this_run.sql
> +               )
❓ Does this fail if they don't have these columns to begin with? Just thinking for the requirements.

2022-11-18 12:34 UTC, rlh1994 commented on models/base/scratch/bigquery/snowplow_ecommerce_base_events_this_run.sql
> +    {% endif %}
❓ I know there was a reason but why was there this hour buffer?

2022-11-18 12:34 UTC, rlh1994 commented on models/products/scratch/snowplow_ecommerce_product_interactions_this_run.sql
> +join {{ ref('snowplow_ecommerce_base_events_this_run') }} as e on pi.event_id = e.event_id
🔧 You could do this without the join can't you? Just bring in these columns within your CTE and then do the loop outside?

2022-11-18 12:34 UTC, rlh1994 commented on models/carts/scratch/snowplow_ecommerce_cart_interactions_this_run.sql
> +where e.ecommerce_action_type IN ('add_to_cart', 'remove_from_cart', 'transaction')
🔧 Again could you bring in all the columns in your CTE and group by them all, then just do your `cart_created` outside to avoid an extra table scan?

2022-11-18 12:34 UTC, rlh1994 commented on models/transactions/scratch/snowplow_ecommerce_transaction_interactions_this_run.sql
> +left join transaction_product_info as tpi on ti.transaction_id = tpi.transaction_id
🔧 Same thing, might be more efficient to avoid a join and just do a huge group by on the rest of the columns. Also, trailing comma.

2022-11-18 12:34 UTC, rlh1994 commented on models/sessions/scratch/snowplow_ecommerce_sessions_this_run.sql
> +    from carts_intermediate
⛏️ This nested with block does not spark joy. Can you either just nest the intermediate query or add that comparison directly to it maybe?

2022-11-18 12:34 UTC, rlh1994 commented on models/sessions/scratch/snowplow_ecommerce_sessions_this_run.sql
> +        MAX(session_entered_at_step) as session_entered_at_step,
❓ How does this work - is the idea you can enter the session before the checkout so no checkout steps have this as True?

2022-11-18 12:34 UTC, rlh1994 commented on models/sessions/scratch/snowplow_ecommerce_sessions_this_run.sql
> +        COUNT(DISTINCT CASE WHEN is_product_transaction THEN event_id END) AS number_product_transactions
💡 Is it worth adding a numberof distinct products viewed in here as well?

2022-11-18 15:34 UTC, rlh1994 requested changes
Just a few questions/small tweaks on the docs side of stuff!

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_overview.md
> +
🛑 Swap out users to sessions

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_table_docs.md
> +Placeholder text.
🛑 Assume this will be added to once it's all finalised

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% enddocs %}
💡 Is it worth documenting this could also be zipcode for our US friends

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% docs col_app_id %}
❓ I assume the answer is no, but there's no way to keep the default ones just in utils (or the planned base package) and use them elsewhere is there? They have to be copied in every time?

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% enddocs %}
🔧 These don't feel right, definetily not the first anwyay. Raised also on the PR for the schema.

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% enddocs %}
❓ I don't know what this means - is this a common ecommerce thing I haven't heard of?

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% enddocs %}
🔧 No longer needed?

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% enddocs %}
🔧 Think this doesn't exist (or I just missed it)

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_atomic_docs.md
> +This context table contains the data generated by the [E-commerce cart context](). This context enables you to track events related to carts, where cart events are used for tracking additions and rem
🔧 Awaiting schema PR to go live?

2022-11-18 15:34 UTC, rlh1994 commented on docs/markdown/snowplow_ecommerce_base_docs.md
> +This incremental table is a manifest of the timestamp of the latest event consumed per model within the `snowplow-ecommerce` package as well as any models leveraging the incremental framework provide
⛏️ Standardise reference to package name

2022-12-09 17:03 UTC, emielver commented on macros/snowplow_delete_from_manifest.sql
> +{% endmacro %}
We use this in `on-run-start`

2022-12-09 17:18 UTC, emielver commented on models/base/scratch/bigquery/snowplow_ecommerce_base_events_this_run.sql
> +    {% endif %}
The hour is relatively arbitrary but basically `derived_tstamp` could be before `collector_tstamp` and this would result in us not processing specific events, so we give the extra buffer here to be sure to include them

2022-12-09 17:24 UTC, emielver commented on models/products/scratch/snowplow_ecommerce_product_interactions_this_run.sql
> +join {{ ref('snowplow_ecommerce_base_events_this_run') }} as e on pi.event_id = e.event_id
Yep, great point!

2022-12-09 17:58 UTC, emielver commented on models/sessions/scratch/snowplow_ecommerce_sessions_this_run.sql
> +        MAX(session_entered_at_step) as session_entered_at_step,
Yep, that's the idea. Although maybe it should be called `session_entered_at_checkout` since it doesn't actually report which step, just whether or not the session was entered at checkout or not

2022-12-09 18:01 UTC, emielver commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% docs col_app_id %}
Yeah unfortunately not that I know of which is quite annoying

2022-12-09 18:05 UTC, emielver commented on docs/markdown/snowplow_ecommerce_common_cols.md
> +{% enddocs %}
I also don't know but I think so, as far as Peter said it should be a well-known thing

2022-12-12 10:30 UTC, rlh1994 requested changes
Just one thing I think, then pulling through the remaining things from previous comments:
1) Add the distinct product views to the sessions table
2) Maybe rename `session_entered_at_step` to `session_entered_at_checkout`
3) Docs for `col_ecommerce_action_type` and `col_ecommerce_action_name` in [docs/markdown/snowplow_ecommerce_common_cols.md](https://github.com/snowplow-incubator/dbt-snowplow-ecommerce/pull/1/files/f3d791be1bb00ef1a0a31fa2c360c11a18a4d5bf#diff-357ea30ad89b2590e4f4062e4ccca725a6a3273582b4b0377e5d6d62671084a2) feels wrong

2022-12-12 10:30 UTC, rlh1994 commented on models/carts/scratch/snowplow_ecommerce_cart_interactions_this_run.sql
>      group by 1
Does this need to be all the other columns as well?

2022-12-12 15:54 UTC, rlh1994 commented on models/sessions/scratch/snowplow_ecommerce_sessions_this_run.sql
> +    from (
What happens if they enter a session with a pre-existing cart? Does the cart count as getting created that session? And what if they empty a cart? I ask because I got some weird numbers when doing the accelerator but not sure how much of that was just the demo data we were submitting...

2022-12-12 22:04 UTC, emielver commented on models/sessions/scratch/snowplow_ecommerce_sessions_this_run.sql
> +    from (
Great point! I'll double check with Peter but AFAIK the intended behaviour is that when users enter a session with a pre-existing cart, that session does NOT count as creating a cart. If they empty the cart within that session, then we do count that as emptying in the cart. In the aggregate, we should have relatively sensible numbers since that cart must have been created in some session. It's also not necessarily wrong to say that no cart was created that session, and as far as I know this is the same behaviour as GA which users should be familiar with, due to the lack of a persistent `cart_id`. So should be all good despite seeing weird-ish numbers, but will double check!

2022-12-14 13:19 UTC, rlh1994 commented on models/base/scratch/bigquery/snowplow_ecommerce_base_events_this_run.sql
> +    a.*
This gives a duplicate `domain_userid` field you'll need to add it to the exclude

2022-12-14 14:18 UTC, rlh1994 commented on models/carts/scratch/snowplow_ecommerce_cart_interactions_this_run.sql
> +)
Swapping this to avoid the extra join outside the CTE has meant this now removed all the non addtocart events, beacuse the default join is an inner join. I think the others are fine because they are either explicity lefts or just event id joins.

2022-12-14 15:10 UTC, emielver commented on models/carts/scratch/snowplow_ecommerce_cart_interactions_this_run.sql
> +)
Yep you're right, made it a left join so now it should be all good!

2022-12-14 15:48 UTC, rlh1994 approved these changes
LGTM!

2022-12-14 16:06 UTC, rlh1994 approved these changes

2022-12-14 16:07 UTC, merged